[colors]
draw_bold_text_with_bright_colors = true

[mouse]
hide_when_typing = true

[cursor]
blink_interval = 750
blink_timeout = 0
#thickness = 0.05
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0
#offset = { y = -4, x = -2 }

[font.normal]
family = "Jetbrains Mono"
#family = "Hack"
#family = "papyrus"
style = "Extralight"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "Full"
dynamic_title = true
resize_increments = true
startup_mode = "Windowed"
decorations_theme_variant = "Dark"
opacity = 0.95
blur = true

[window.dimensions]
columns = 102
lines = 26

[window.padding]
x = 12
y = 12

[general]
live_config_reload = true
import = [
  "dark-theme.toml",
  #"light-theme.toml",
]

[keyboard]
bindings = [ { key = "Back", mods = "Control", chars = "\u0017" } ]

